### ISSUE TITLE
Optionally Fail Checks When Body Check does not pass

### ISSUE THREAD

**Issue by mtfoley** [mtfoley/pr-compliance-action#182]
**Is your feature request related to a problem? Please describe.**
per @nkapinos:
> Hi Matthew!
I've been playing around with this Github Action, and found it useful to be
able to check for Issues linked in a PR.  I'm looking to enforce this
development practice.  Yes, adding a setting so bodyCheckOutcome will fail
and block PR merge (like titleCheck does) is the behavior I'm looking for.
Cheers,
Nate

See also PR #181 

**Describe the solution you'd like**
Provide a way for the action to show a failing check rather than only a warning when the body regex is not matched (e.g. a PR has no linked issue).

**Describe alternatives you've considered**
changing the action to always have a failing check when the body regex is not matched. This would be a breaking change though.

**Additional context**
N/A

**Comment by mtfoley** [comment]
@nkapinos, I started a feature branch for this. I'm curious how it fits your use case:
https://github.com/mtfoley/pr-compliance-action/tree/body-fail-option

You should be able to use it in your workflow file like this:
```yaml
jobs:
  pr-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@body-fail-option
        with:
          # all inputs are optional
          body-fail: true
          # other options
```
