### ISSUE TITLE
Disallow leading zeros on issue IDs by default

### ISSUE THREAD

**Issue by RebeccaStevens** [mtfoley/pr-compliance-action#346]
## Describe the bug
By default, leading zeros are currently allowed. They shouldn't be.

## To Reproduce
Add leading zeros to issue ID `fix #003`

## Workflow File Contents
```yml
jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@main
```

## Expected behavior
Leading zeros should not be allowed.

## Additional context
Some issue templates like to use `fix #000` in them. They then expect the PR author to modify this. If they don't compliance shouldn't be marked as meet.

## Suggested change

Change the default `body-regex` from `(fix|resolv|clos)(e)*(s|d)* #\d+` to `(fix|resolv|clos)(e)*(s|d)* #[1-9]\d*`.

### Better Regex:

`(fix(es|ed)?|((resolve|close)(s|d)?)) #[1-9]\d*`

This regex also fixes the issue of thing like `fixs #1` and `closeeeeeeeeeeeeeeeeeeeed #1` being valid.
