### ISSUE TITLE
Issue Labels Check may Require `issues: read` Permissions

### ISSUE THREAD

**Issue by mtfoley** [mtfoley/pr-compliance-action#377]
**Describe the bug**
The Issue Labels check doesn't find errors for a private repo if the permissions don't include `issues: read` on the workflow file.  This is unlikely to be an issue on public repos, but in testing on a private fork of a private repo, this is what I've seen.  When `issues: read` is added to workflow file, the action works as expected and flags the PR linked to an issue that doesn't include the right labels.

**Workflow File Contents**
```yml
name: PR Compliance

on:
  pull_request_target:
    types: [opened, edited, reopened]

# Action should have write permission to make updates to PR
permissions:
  pull-requests: write

jobs:
  pr-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@octokit-errors
        with:
          # all inputs are optional
          body-auto-close: false
          ignore-team-members: false
          issue-labels: |
            accepting-prs
          watch-files: |
            package.json
            npm-shrinkwrap.json
```

**Expected behavior**
Action flags the PR linked to an issue that doesn't include the right labels.

**Screenshots**
N/A

**Additional context**
It may be that we need to do some different error handling with a GraphQL than with Rest since the error modes are different. e.g. GraphQL may happily return an HTTP 200 and report the error in JSON response rather than a status code.
